### ISSUE TITLE
Enable user to download folder content in one go

### ISSUE THREAD

**Issue by arnima-github** [ices-taf/doc#138]
### Summary
Download a full analysis (scripts, data, model and results) to the local drive as a zip folder

### Tasks required
- [x] Zip option in controller
- [x] develop token authentication in backend

**Comment by colinpmillar** [comment]
Token auth can be done like this:
https://logcorner.com/token-based-authentication-using-asp-net-web-api-core/

**Comment by colinpmillar** [comment]
Complete!
