### ISSUE TITLE
Update main taf.ices.dk landing page

### ISSUE THREAD

**Issue by arnima-github** [ices-taf/doc#142]
### Ideas:
- [x] change db to data
- [x] make it easier to see TAF diagram
- [x] make it easier to see TAF flyer
- [x] make it easier to link to TAF tutorial video

### notes

* Terhi said she could help to simplify the message for the main page.

**Comment by neil-ices-dk** [comment]
1. change db to data - DONE
2. make it easier to see TAF diagram - WHICH DIAGRAM AND WHAT DID YOU HAVE IN MIND?
3. make it easier to see TAF flyer - WHERE IS THE FLYER LINK?

**Comment by arnima-github** [comment]
We use the
* TAF diagram (https://ices-taf-dev.github.io/png/taf-diagram.png) and
* TAF flyer (https://ices-taf-dev.github.io/pdf/taf-flyer.pdf)
a lot when we're explaining TAF to people.

These are currently not very easy to find from taf.ices.dk, but are on the development page (https://ices-taf-dev.github.io).

**Comment by neil-ices-dk** [comment]
ok, i've contacted Communications as we need to make these look a little slicker - when we have an agreed version we will post these to the main landing page and then you can link to these :).

So, it might take a little longer than a quick fix

**Comment by arnima-github** [comment]
That sounds good. Looking at the links on taf.ices.dk, they could be updated as well.

Back when the taf.ices.dk webpage was put together, we were eager to show all the cool new things. By now, the links have become too many, and some important ones are missing (diagram, flyer, icesTAF package).

**Comment by arnima-github** [comment]
![proposal](https://user-images.githubusercontent.com/3720910/35687037-f99a53a0-076d-11e8-8f7a-a39a62b38ed7.png)

**Comment by arnima-github** [comment]
The above image shows how the links could be simplified.
1. The purpose of "Jumping to the TAF on GitHub" is not clear. This link could be renamed to "Explore TAF example scripts.
2. The "ICES GitHub sites" link is probably not needed here. The topic is covered by the "Software and Code" link (on the left bar) and also on the TAF development page.
3. The "Introduction to ICES on GitHub (slides)" should probably be moved to the "Software and Code" page (linked on the left bar).
4. The TAF-related R packages probably don't need to be listed here. They are explained on the TAF development page.
5. R packages related to web services should probably be listed on the "Web Services" page (linked on the left bar).
6. The "Using Web Services from R (slides)" should probably be moved to the "Web Services" page (linked on the left bar).

**Comment by arnima-github** [comment]
We will soon be adding a link to the video and a user handbook. For the time being, pruning the links on the right down to 5 might be a good spring cleaning :)

**Comment by arnima-github** [comment]
After development slows down (maybe 2019) and the web server is fully functional, we can restructure the web presence again. Probably reduce the amount of material on the development page, or remove it completely.

**Comment by colinpmillar** [comment]
Suggested structure for landing page:

level 1:
* TAF APP
* EXAMPLE: North Sea Spotted Ray
* EXAMPLE: Icelandic Haddock

level 2: Resources
* flyer
* Introductory tutorial (text)
* Introductory tutorial (video)
* Procedure to get an assessment into TAF
* ices tools productions (github)

**Comment by colinpmillar** [comment]
Hi @neil-ices-dk  - FYI I have added working links to the list above

**Comment by neil-ices-dk** [comment]
@neil-ices-dk to do on Thursday afternoon; have asked Comms to make a web friendly version of the final flyer (fold-out)

**Comment by neil-ices-dk** [comment]
Fresh page now ready :)
http://ices.dk/marine-data/tools/Pages/transparent-assessment-framework.aspx 

![image](https://user-images.githubusercontent.com/23527005/49591451-cca6c380-f96e-11e8-9c10-80f3af4d06fd.png)
