### ISSUE TITLE
GFCM side event, TAF workshop

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-taf/doc#150]
### Summary
GFCM are running a largeish event (fishforum). ICES have been invited to propose a side event and we think that TAF is what we should focus on/sell to the Med. If we agree, then we will need to discuss format etc. and also submit a short abstract by April 1
### Tasks required
- [x] Make a decision whether we can attend (should we be successful)
- [x] Make abstract and submit
- [ ] Plan workshop
[GFCM-FishForum2018-Workshop-Side-event-proposals.pdf](https://github.com/ices-taf/doc/files/1760112/GFCM-FishForum2018-Workshop-Side-event-proposals.pdf)

**Comment by colinpmillar** [comment]
Planning split into seperate issue:
FAO Rome event planning #212
