### ISSUE TITLE
Investigate use of RStudio server as user interface

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#24]

**Comment by colinpmillar** [comment]
Progress so far:
* Have a TAF server setup: windows server 2016.
* Trying to install Rstudio server which requires linux OS.
* Have installed Docker for windows to get a linux container running - work in progress.

Next steps:
* contact Mike to allow the server to publish a webpage internally.

**Comment by einarhjorleifsson** [comment]
exciting that you are moving from planning to in_progress
e

**Comment by colinpmillar** [comment]
Progress:
* TAF server running internally, hosting a web page and running R
* not yet able to get Docker running, so no linux OS container possible yet
* Now considering the alternative which is to set up a dedicated Linux server running R studio server

**Comment by colinpmillar** [comment]
Putting this on the back burner for now as we have a method to edit and run scripts online without the need for R studio
