### ISSUE TITLE
Publish icesDatras on CRAN

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#281]
From: https://github.com/ices-tools-prod/icesDatras/issues/40

The icesDatras package has not been updated on CRAN for a while, so its time! :)

- [x] run devtools checks
- [x] update DESCRIPTION version
- [x] change maintainer to Cecilia
- [x] Add github url to DESCRIPTION
- [x] CRAN checks
- [x] release to CRAN
- [x] any corrections modifications required by CRAN

**Comment by cekv** [comment]
Have involved Adriana to add to this package, at least all DATRAS API webservice products.
