### ISSUE TITLE
Fix issues with icesDatras::getCatchWgt.

### ISSUE THREAD

**Issue by cekv** [ices-taf/doc#286]
There is an issue with countries sharing ships in NS-IBTS and BITS (SE and DK) which means that the key is identical for some rows. I think this can be circumvented by adding country to that key?!

Jobs required:
- [x] update code in icesDATRAS locally
- [x] run devtools::document() and devtools::check()
- [x] update version number in DESCRIPTION file
- [ ] commit and push to ices-tools-dev/icesDatras
- [ ] later: check build on https://ices-tools-prod.r-universe.dev/ui#builds

**Comment by colinpmillar** [comment]
Lines to change:
https://github.com/ices-tools-prod/icesDatras/blob/d4e9d7e18d97f8792ffcf6eb6331c4541fa4efbe/R/getCatchWgt.R#L39-L41

**Comment by colinpmillar** [comment]
proposed change:
```r
  hh$HaulID <- with(hh, paste(Year, Quarter, Ship, Country, StNo, HaulNo, sep="."))
  hl$HaulID <- with(hl, paste(Year, Quarter, Ship, Country, StNo, HaulNo, sep="."))
  key <- c("Year", "Quarter", "Ship", "StNo", "HaulNo", "HaulID")
```

**Comment by cekv** [comment]
This line needed "country" added as well
´´´r
 key <- c("Year", "Quarter", "Ship", "StNo", "HaulNo", "HaulID")
 ´´´

**Comment by cekv** [comment]
DATRAS package published to CRAN with the fix
