### ISSUE TITLE
Develop Survey for WKTAF requirements

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#290]
## tasks
- [x] list of EGs and POs to contact
- [x] design questions
- [x] send!

**Comment by colinpmillar** [comment]
We can use a combo of SID and CRM to find the list of EGs and POs - I will provide some code to help with the POs bit

**Comment by cekv** [comment]
list of EGs and POs to contact - sent to all POs with stock assessors in their EGs

**Comment by cekv** [comment]
So far 21 recipients have replied 
[WKTAF Requirement(1-21).xlsx](https://github.com/ices-taf/doc/files/7821531/WKTAF.Requirement.1-21.xlsx)
