### ISSUE TITLE
TAF presentation for WGs (focus on use of SAG web services)

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#41]
Depends on:

- [x] #6
- [x] #38 

related to:
- [x] ices-tools-prod/icesSAG#50
- [ ] ices-tools-prod/icesSAG#41

**Comment by colinpmillar** [comment]
Will upload presentation to github, then will sign off.

**Comment by colinpmillar** [comment]
Presented to:
* WGNSSK
* WGDEEP

**Comment by neil-ices-dk** [comment]
Add to main ICES web site

**Comment by colinpmillar** [comment]
Presentation are on intranet here:
* http://intranet.ices.local/datacentre/SitePages/Home.aspx?RootFolder=%2Fdatacentre%2FShared%20Documents%2FTAF%20Assessment%20Framework%2FPresentations%2F2017_xx_xx_wg_presentations
where would be the best place for them to go?
* http://taf.ices.local/TAF/ ? or
* http://taf.ices.dk  ?

**Comment by neil-ices-dk** [comment]
suggest it needs to go on main website (/marinedocs/) so that it is more discoverable; will add a new docs/resources box to http://taf.ices.dk

**Comment by neil-ices-dk** [comment]
@Carlos - have added a link on SAG landing page in [more info] box to Colin's ppt on web services and R integration http://ices.dk/marine-data/Documents/StockAssessment/intro-sag.pdf 
Suggest you may want to also add something directly on http://standardgraphs.ices.dk/webservices.aspx but up to you

**Comment by neil-ices-dk** [comment]
http://ices.dk/marine-data/tools/Pages/transparent-assessment-framework.aspx updated with a documents right hand nav and links to the slides
