### ISSUE TITLE
North Sea cod: web services (input data online)

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#45]

**Comment by colinpmillar** [comment]
Data is available on Stockassessment.org here:
https://stockassessment.org/datadisk/stockassessment/userdirs/user3/nscod16-ass02/

Should we try and import it into TAF?

**Comment by neil-ices-dk** [comment]
for /data on SAO.org, need to know where the data came from (source/location/log changes) before it comes into SAO.org

**Comment by neil-ices-dk** [comment]
when testing, look at versioning (DateofCalculation)

**Comment by neil-ices-dk** [comment]
also (for Vaishav), the number of decimal places is different between the web service and the web GUI download

**Comment by vaishav** [comment]
Its done. good if you test at your end.
https://datras.ices.dk/WebServices/DATRASWebService.asmx/getIndices?survey=NS-IBTS&year=2010&quarter=1&species=126436

**Comment by colinpmillar** [comment]
Done: up at last here:
http://taf.ices.local/TAF/fs/2016_cod-347d/raw/

full assessment here:
http://taf.ices.local/TAF/App/ManageTAF#!/analysis/2016_cod-347d
