### ISSUE TITLE
TAF cartoon diagram (was Brainstorm features of TAF)

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#6]
Design a new TAF diagram showing the connections to existing systems (i.e. stock assessment.org) and how TAF will interact with these systems.  This diagram will be of use to developers seeking to interact with TAF, such as stockassessment.org, and the REDUS project.

**Comment by neil-ices-dk** [comment]
overview (so far) of features and connections

**Comment by colinpmillar** [comment]
Diagrams complete and presented to DTU
