### ISSUE TITLE
Show plots of standard assessment results on assessment summary page

### ISSUE THREAD

**Issue by colinpmillar** [ices-taf/doc#7]

**Comment by colinpmillar** [comment]
Testing the interface at:
http://taf.ices.local/TAF/App/Plots

**Comment by neil-ices-dk** [comment]
link to #46 viewing outputs task

**Comment by colinpmillar** [comment]
done - see for example:
http://taf.ices.local/TAF/App/ViewTAF#!/2015_had-iceg
